name: dart_cast
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  collection: ^1.19.0
  gql: ^1.0.0+1
  path: ^1.9.0
  source_gen: ^1.5.0
  # path: ^1.8.0

dev_dependencies:
  strict: ^2.1.0
  custom_lint: ^0.6.4

  test: ^1.24.0
  build_runner: ^2.4.11
  build_test: ^2.2.2
  coverage: ^1.9.0
  rps: ^0.8.2
  mocktail: ^1.0.4

scripts:
  test: dart run coverage:test_with_coverage
  coverage: genhtml -o coverage/html coverage/lcov.info && open coverage/html/index.html
