type SimpleType {
  stringField: String!
  doubleField: Float!
  boolField: Boolean!
  intField: Int!
  nullableField: String
  listField: [String!]!
  nullableListField: [String!]
  listNullableField: [String]!
  doubleNullableField: [String]
}

input PositionalParameterInput {
  foo: String
}

input InsideInputParameterWithReferenceInput {
  foo: String
  backReference: NamedParameterInput
}

input NamedParameterInput {
  foo: Int
  insideInputParameter: InsideInputParameterWithReferenceInput
}

type Query {
  simpleTypeQuery(
    emptyParameter: PositionalParameterInput!
    namedParameter: NamedParameterInput!
    defaultValue: String! = "'foo'"
  ): [SimpleType!]!
  simpleTypeQueryNullable: SimpleType
  simpleTypeList: [SimpleType!]!
}

type Mutation {

}